language: java
notifications:
  slack:
    secure: U+Xfg5/isDKa6JWpy98kauwcirWDAGlmVYcqBRkNBztH6uKvpJQX94Ftj3ciRyWU4f2Dm+fmBRtMnCsRBOied7XK8r+J/MFL7E+jP3FHT/3v/sRROhS15nX3vPPJDVMpU5G3UDe2d1n8VE6RyK6a6bGvOaFFBnt9WLdyoKKmM2gmR6ie/iBIJlQdYy4nMuu8Q0ExDuEX6gWCAyCzl9iC3uUHHOPCCuQPiEDD9zN17UYI+kbcYNjIbVJItyjGG9W3oBcVZm7Rn8mpB+kaV33iioMqz6oUC5vzPjwDw0vVk9AivZH1GQDhDvuJMFvFgJ5w7lj+rV6J6c9RvpHpMTZGFy4Fx7HoaTukqO53g74Vz63c9ql/L+hRXbkO7pkfB4PQJSpdF0Dc7Zq8hRZMcoMo6YW0+zYH0PtSESMo4+FK8WtmBtRwKcWCAaPdsDsYtnhj3ezjLijEqeKuk98AaV11Dik+C6/xmhmmfWqe+JizmSnCrRQz4h7H/2vsX8KSDip8hftvimjRkx0nYLsEwEjy7k5QmFsJ8zK47XJPUxiEimW86xoOP9Jesvtx+Ns+vRNa6wqXok2WM5cwD2oYQ7xdopBh98rQdrQiKnwFU6NE8us1tyKNwnJ2xuNrXbt+7PcJodCXTIlOkQIIAGUQx2CAR4TLAk564e/hqD+GW9102zw=
    on_success: change # default: always
    on_failure: always # default: always
